blank_issues_enabled: false
contact_links:
  - name: Help / Question / Feature request
    url: https://github.com/ben-rogerson/twin.macro/discussions/new
    about: 'If you have a question, need help or have an idea please ask a question in the discussion forum'
