name: Notification on push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: twin
          DISCORD_AVATAR: https://i.imgur.com/lUMLFrH.png
        uses: Ilshidur/action-discord@master
